/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppHoursRouteImport } from './routes/_app.hours'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppPurchasesIndexRouteImport } from './routes/_app.purchases.index'
import { Route as AppOutreachIndexRouteImport } from './routes/_app.outreach.index'
import { Route as AppOpiIndexRouteImport } from './routes/_app.opi.index'
import { Route as AppNotificationsIndexRouteImport } from './routes/_app.notifications.index'
import { Route as AppBuildIndexRouteImport } from './routes/_app.build.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppPurchasesNewRouteImport } from './routes/_app.purchases.new'
import { Route as AppPurchasesIdRouteImport } from './routes/_app.purchases.$id'
import { Route as AppOutreachLogRouteImport } from './routes/_app.outreach.log'
import { Route as AppOutreachHistoryRouteImport } from './routes/_app.outreach.history'
import { Route as AppOutreachCheckInRouteImport } from './routes/_app.outreach.check-in'
import { Route as AppOpiNewRouteImport } from './routes/_app.opi.new'
import { Route as AppOpiIdRouteImport } from './routes/_app.opi.$id'
import { Route as AppNotificationsPreferencesRouteImport } from './routes/_app.notifications.preferences'
import { Route as AppBuildHistoryRouteImport } from './routes/_app.build.history'
import { Route as AppBuildCheckInRouteImport } from './routes/_app.build.check-in'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppAdminCronJobsRouteImport } from './routes/_app.admin.cron-jobs'
import { Route as AppAdminPurchasesIndexRouteImport } from './routes/_app.admin.purchases.index'
import { Route as AppAdminOpiIndexRouteImport } from './routes/_app.admin.opi.index'
import { Route as AppAdminMembersIndexRouteImport } from './routes/_app.admin.members.index'
import { Route as AppOutreachEventsIdRouteImport } from './routes/_app.outreach.events.$id'
import { Route as AppBuildSessionsIdRouteImport } from './routes/_app.build.sessions.$id'
import { Route as AppAdminReportsPurchasesRouteImport } from './routes/_app.admin.reports.purchases'
import { Route as AppAdminReportsOpiRouteImport } from './routes/_app.admin.reports.opi'
import { Route as AppAdminReportsHoursRouteImport } from './routes/_app.admin.reports.hours'
import { Route as AppAdminOutreachAttendanceRouteImport } from './routes/_app.admin.outreach.attendance'
import { Route as AppAdminNotificationsTemplatesRouteImport } from './routes/_app.admin.notifications.templates'
import { Route as AppAdminMembersPendingRouteImport } from './routes/_app.admin.members.pending'
import { Route as AppAdminMembersIdRouteImport } from './routes/_app.admin.members.$id'
import { Route as AppAdminBuildZonesRouteImport } from './routes/_app.admin.build.zones'
import { Route as AppAdminBuildAttendanceRouteImport } from './routes/_app.admin.build.attendance'
import { Route as AppAdminOutreachIndividualIndexRouteImport } from './routes/_app.admin.outreach.individual.index'
import { Route as AppAdminOutreachEventsIndexRouteImport } from './routes/_app.admin.outreach.events.index'
import { Route as AppAdminBuildScheduleIndexRouteImport } from './routes/_app.admin.build.schedule.index'
import { Route as AppAdminPurchasesIdReviewRouteImport } from './routes/_app.admin.purchases.$id.review'
import { Route as AppAdminOutreachEventsNewRouteImport } from './routes/_app.admin.outreach.events.new'
import { Route as AppAdminOpiIdReviewRouteImport } from './routes/_app.admin.opi.$id.review'
import { Route as AppAdminBuildScheduleNewRouteImport } from './routes/_app.admin.build.schedule.new'
import { Route as AppAdminOutreachIndividualIdReviewRouteImport } from './routes/_app.admin.outreach.individual.$id.review'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHoursRoute = AppHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesIndexRoute = AppPurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachIndexRoute = AppOutreachIndexRouteImport.update({
  id: '/outreach/',
  path: '/outreach/',
  getParentRoute: () => AppRoute,
} as any)
const AppOpiIndexRoute = AppOpiIndexRouteImport.update({
  id: '/opi/',
  path: '/opi/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildIndexRoute = AppBuildIndexRouteImport.update({
  id: '/build/',
  path: '/build/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppPurchasesNewRoute = AppPurchasesNewRouteImport.update({
  id: '/purchases/new',
  path: '/purchases/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesIdRoute = AppPurchasesIdRouteImport.update({
  id: '/purchases/$id',
  path: '/purchases/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachLogRoute = AppOutreachLogRouteImport.update({
  id: '/outreach/log',
  path: '/outreach/log',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachHistoryRoute = AppOutreachHistoryRouteImport.update({
  id: '/outreach/history',
  path: '/outreach/history',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachCheckInRoute = AppOutreachCheckInRouteImport.update({
  id: '/outreach/check-in',
  path: '/outreach/check-in',
  getParentRoute: () => AppRoute,
} as any)
const AppOpiNewRoute = AppOpiNewRouteImport.update({
  id: '/opi/new',
  path: '/opi/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOpiIdRoute = AppOpiIdRouteImport.update({
  id: '/opi/$id',
  path: '/opi/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsPreferencesRoute =
  AppNotificationsPreferencesRouteImport.update({
    id: '/notifications/preferences',
    path: '/notifications/preferences',
    getParentRoute: () => AppRoute,
  } as any)
const AppBuildHistoryRoute = AppBuildHistoryRouteImport.update({
  id: '/build/history',
  path: '/build/history',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildCheckInRoute = AppBuildCheckInRouteImport.update({
  id: '/build/check-in',
  path: '/build/check-in',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCronJobsRoute = AppAdminCronJobsRouteImport.update({
  id: '/cron-jobs',
  path: '/cron-jobs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPurchasesIndexRoute = AppAdminPurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminOpiIndexRoute = AppAdminOpiIndexRouteImport.update({
  id: '/opi/',
  path: '/opi/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMembersIndexRoute = AppAdminMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppOutreachEventsIdRoute = AppOutreachEventsIdRouteImport.update({
  id: '/outreach/events/$id',
  path: '/outreach/events/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildSessionsIdRoute = AppBuildSessionsIdRouteImport.update({
  id: '/build/sessions/$id',
  path: '/build/sessions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReportsPurchasesRoute =
  AppAdminReportsPurchasesRouteImport.update({
    id: '/reports/purchases',
    path: '/reports/purchases',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminReportsOpiRoute = AppAdminReportsOpiRouteImport.update({
  id: '/reports/opi',
  path: '/reports/opi',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReportsHoursRoute = AppAdminReportsHoursRouteImport.update({
  id: '/reports/hours',
  path: '/reports/hours',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminOutreachAttendanceRoute =
  AppAdminOutreachAttendanceRouteImport.update({
    id: '/outreach/attendance',
    path: '/outreach/attendance',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminNotificationsTemplatesRoute =
  AppAdminNotificationsTemplatesRouteImport.update({
    id: '/notifications/templates',
    path: '/notifications/templates',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminMembersPendingRoute = AppAdminMembersPendingRouteImport.update({
  id: '/members/pending',
  path: '/members/pending',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMembersIdRoute = AppAdminMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBuildZonesRoute = AppAdminBuildZonesRouteImport.update({
  id: '/build/zones',
  path: '/build/zones',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBuildAttendanceRoute = AppAdminBuildAttendanceRouteImport.update({
  id: '/build/attendance',
  path: '/build/attendance',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminOutreachIndividualIndexRoute =
  AppAdminOutreachIndividualIndexRouteImport.update({
    id: '/outreach/individual/',
    path: '/outreach/individual/',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminOutreachEventsIndexRoute =
  AppAdminOutreachEventsIndexRouteImport.update({
    id: '/outreach/events/',
    path: '/outreach/events/',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminBuildScheduleIndexRoute =
  AppAdminBuildScheduleIndexRouteImport.update({
    id: '/build/schedule/',
    path: '/build/schedule/',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminPurchasesIdReviewRoute =
  AppAdminPurchasesIdReviewRouteImport.update({
    id: '/purchases/$id/review',
    path: '/purchases/$id/review',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminOutreachEventsNewRoute =
  AppAdminOutreachEventsNewRouteImport.update({
    id: '/outreach/events/new',
    path: '/outreach/events/new',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminOpiIdReviewRoute = AppAdminOpiIdReviewRouteImport.update({
  id: '/opi/$id/review',
  path: '/opi/$id/review',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBuildScheduleNewRoute =
  AppAdminBuildScheduleNewRouteImport.update({
    id: '/build/schedule/new',
    path: '/build/schedule/new',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminOutreachIndividualIdReviewRoute =
  AppAdminOutreachIndividualIdReviewRouteImport.update({
    id: '/outreach/individual/$id/review',
    path: '/outreach/individual/$id/review',
    getParentRoute: () => AppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/hours': typeof AppHoursRoute
  '/profile': typeof AppProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/cron-jobs': typeof AppAdminCronJobsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/build/check-in': typeof AppBuildCheckInRoute
  '/build/history': typeof AppBuildHistoryRoute
  '/notifications/preferences': typeof AppNotificationsPreferencesRoute
  '/opi/$id': typeof AppOpiIdRoute
  '/opi/new': typeof AppOpiNewRoute
  '/outreach/check-in': typeof AppOutreachCheckInRoute
  '/outreach/history': typeof AppOutreachHistoryRoute
  '/outreach/log': typeof AppOutreachLogRoute
  '/purchases/$id': typeof AppPurchasesIdRoute
  '/purchases/new': typeof AppPurchasesNewRoute
  '/admin/': typeof AppAdminIndexRoute
  '/build/': typeof AppBuildIndexRoute
  '/notifications/': typeof AppNotificationsIndexRoute
  '/opi/': typeof AppOpiIndexRoute
  '/outreach/': typeof AppOutreachIndexRoute
  '/purchases/': typeof AppPurchasesIndexRoute
  '/admin/build/attendance': typeof AppAdminBuildAttendanceRoute
  '/admin/build/zones': typeof AppAdminBuildZonesRoute
  '/admin/members/$id': typeof AppAdminMembersIdRoute
  '/admin/members/pending': typeof AppAdminMembersPendingRoute
  '/admin/notifications/templates': typeof AppAdminNotificationsTemplatesRoute
  '/admin/outreach/attendance': typeof AppAdminOutreachAttendanceRoute
  '/admin/reports/hours': typeof AppAdminReportsHoursRoute
  '/admin/reports/opi': typeof AppAdminReportsOpiRoute
  '/admin/reports/purchases': typeof AppAdminReportsPurchasesRoute
  '/build/sessions/$id': typeof AppBuildSessionsIdRoute
  '/outreach/events/$id': typeof AppOutreachEventsIdRoute
  '/admin/members/': typeof AppAdminMembersIndexRoute
  '/admin/opi/': typeof AppAdminOpiIndexRoute
  '/admin/purchases/': typeof AppAdminPurchasesIndexRoute
  '/admin/build/schedule/new': typeof AppAdminBuildScheduleNewRoute
  '/admin/opi/$id/review': typeof AppAdminOpiIdReviewRoute
  '/admin/outreach/events/new': typeof AppAdminOutreachEventsNewRoute
  '/admin/purchases/$id/review': typeof AppAdminPurchasesIdReviewRoute
  '/admin/build/schedule/': typeof AppAdminBuildScheduleIndexRoute
  '/admin/outreach/events/': typeof AppAdminOutreachEventsIndexRoute
  '/admin/outreach/individual/': typeof AppAdminOutreachIndividualIndexRoute
  '/admin/outreach/individual/$id/review': typeof AppAdminOutreachIndividualIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/hours': typeof AppHoursRoute
  '/profile': typeof AppProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/cron-jobs': typeof AppAdminCronJobsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/build/check-in': typeof AppBuildCheckInRoute
  '/build/history': typeof AppBuildHistoryRoute
  '/notifications/preferences': typeof AppNotificationsPreferencesRoute
  '/opi/$id': typeof AppOpiIdRoute
  '/opi/new': typeof AppOpiNewRoute
  '/outreach/check-in': typeof AppOutreachCheckInRoute
  '/outreach/history': typeof AppOutreachHistoryRoute
  '/outreach/log': typeof AppOutreachLogRoute
  '/purchases/$id': typeof AppPurchasesIdRoute
  '/purchases/new': typeof AppPurchasesNewRoute
  '/admin': typeof AppAdminIndexRoute
  '/build': typeof AppBuildIndexRoute
  '/notifications': typeof AppNotificationsIndexRoute
  '/opi': typeof AppOpiIndexRoute
  '/outreach': typeof AppOutreachIndexRoute
  '/purchases': typeof AppPurchasesIndexRoute
  '/admin/build/attendance': typeof AppAdminBuildAttendanceRoute
  '/admin/build/zones': typeof AppAdminBuildZonesRoute
  '/admin/members/$id': typeof AppAdminMembersIdRoute
  '/admin/members/pending': typeof AppAdminMembersPendingRoute
  '/admin/notifications/templates': typeof AppAdminNotificationsTemplatesRoute
  '/admin/outreach/attendance': typeof AppAdminOutreachAttendanceRoute
  '/admin/reports/hours': typeof AppAdminReportsHoursRoute
  '/admin/reports/opi': typeof AppAdminReportsOpiRoute
  '/admin/reports/purchases': typeof AppAdminReportsPurchasesRoute
  '/build/sessions/$id': typeof AppBuildSessionsIdRoute
  '/outreach/events/$id': typeof AppOutreachEventsIdRoute
  '/admin/members': typeof AppAdminMembersIndexRoute
  '/admin/opi': typeof AppAdminOpiIndexRoute
  '/admin/purchases': typeof AppAdminPurchasesIndexRoute
  '/admin/build/schedule/new': typeof AppAdminBuildScheduleNewRoute
  '/admin/opi/$id/review': typeof AppAdminOpiIdReviewRoute
  '/admin/outreach/events/new': typeof AppAdminOutreachEventsNewRoute
  '/admin/purchases/$id/review': typeof AppAdminPurchasesIdReviewRoute
  '/admin/build/schedule': typeof AppAdminBuildScheduleIndexRoute
  '/admin/outreach/events': typeof AppAdminOutreachEventsIndexRoute
  '/admin/outreach/individual': typeof AppAdminOutreachIndividualIndexRoute
  '/admin/outreach/individual/$id/review': typeof AppAdminOutreachIndividualIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/hours': typeof AppHoursRoute
  '/_app/profile': typeof AppProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/admin/cron-jobs': typeof AppAdminCronJobsRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/build/check-in': typeof AppBuildCheckInRoute
  '/_app/build/history': typeof AppBuildHistoryRoute
  '/_app/notifications/preferences': typeof AppNotificationsPreferencesRoute
  '/_app/opi/$id': typeof AppOpiIdRoute
  '/_app/opi/new': typeof AppOpiNewRoute
  '/_app/outreach/check-in': typeof AppOutreachCheckInRoute
  '/_app/outreach/history': typeof AppOutreachHistoryRoute
  '/_app/outreach/log': typeof AppOutreachLogRoute
  '/_app/purchases/$id': typeof AppPurchasesIdRoute
  '/_app/purchases/new': typeof AppPurchasesNewRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/build/': typeof AppBuildIndexRoute
  '/_app/notifications/': typeof AppNotificationsIndexRoute
  '/_app/opi/': typeof AppOpiIndexRoute
  '/_app/outreach/': typeof AppOutreachIndexRoute
  '/_app/purchases/': typeof AppPurchasesIndexRoute
  '/_app/admin/build/attendance': typeof AppAdminBuildAttendanceRoute
  '/_app/admin/build/zones': typeof AppAdminBuildZonesRoute
  '/_app/admin/members/$id': typeof AppAdminMembersIdRoute
  '/_app/admin/members/pending': typeof AppAdminMembersPendingRoute
  '/_app/admin/notifications/templates': typeof AppAdminNotificationsTemplatesRoute
  '/_app/admin/outreach/attendance': typeof AppAdminOutreachAttendanceRoute
  '/_app/admin/reports/hours': typeof AppAdminReportsHoursRoute
  '/_app/admin/reports/opi': typeof AppAdminReportsOpiRoute
  '/_app/admin/reports/purchases': typeof AppAdminReportsPurchasesRoute
  '/_app/build/sessions/$id': typeof AppBuildSessionsIdRoute
  '/_app/outreach/events/$id': typeof AppOutreachEventsIdRoute
  '/_app/admin/members/': typeof AppAdminMembersIndexRoute
  '/_app/admin/opi/': typeof AppAdminOpiIndexRoute
  '/_app/admin/purchases/': typeof AppAdminPurchasesIndexRoute
  '/_app/admin/build/schedule/new': typeof AppAdminBuildScheduleNewRoute
  '/_app/admin/opi/$id/review': typeof AppAdminOpiIdReviewRoute
  '/_app/admin/outreach/events/new': typeof AppAdminOutreachEventsNewRoute
  '/_app/admin/purchases/$id/review': typeof AppAdminPurchasesIdReviewRoute
  '/_app/admin/build/schedule/': typeof AppAdminBuildScheduleIndexRoute
  '/_app/admin/outreach/events/': typeof AppAdminOutreachEventsIndexRoute
  '/_app/admin/outreach/individual/': typeof AppAdminOutreachIndividualIndexRoute
  '/_app/admin/outreach/individual/$id/review': typeof AppAdminOutreachIndividualIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending-approval'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/hours'
    | '/profile'
    | '/auth/callback'
    | '/admin/cron-jobs'
    | '/admin/settings'
    | '/build/check-in'
    | '/build/history'
    | '/notifications/preferences'
    | '/opi/$id'
    | '/opi/new'
    | '/outreach/check-in'
    | '/outreach/history'
    | '/outreach/log'
    | '/purchases/$id'
    | '/purchases/new'
    | '/admin/'
    | '/build/'
    | '/notifications/'
    | '/opi/'
    | '/outreach/'
    | '/purchases/'
    | '/admin/build/attendance'
    | '/admin/build/zones'
    | '/admin/members/$id'
    | '/admin/members/pending'
    | '/admin/notifications/templates'
    | '/admin/outreach/attendance'
    | '/admin/reports/hours'
    | '/admin/reports/opi'
    | '/admin/reports/purchases'
    | '/build/sessions/$id'
    | '/outreach/events/$id'
    | '/admin/members/'
    | '/admin/opi/'
    | '/admin/purchases/'
    | '/admin/build/schedule/new'
    | '/admin/opi/$id/review'
    | '/admin/outreach/events/new'
    | '/admin/purchases/$id/review'
    | '/admin/build/schedule/'
    | '/admin/outreach/events/'
    | '/admin/outreach/individual/'
    | '/admin/outreach/individual/$id/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pending-approval'
    | '/signup'
    | '/dashboard'
    | '/hours'
    | '/profile'
    | '/auth/callback'
    | '/admin/cron-jobs'
    | '/admin/settings'
    | '/build/check-in'
    | '/build/history'
    | '/notifications/preferences'
    | '/opi/$id'
    | '/opi/new'
    | '/outreach/check-in'
    | '/outreach/history'
    | '/outreach/log'
    | '/purchases/$id'
    | '/purchases/new'
    | '/admin'
    | '/build'
    | '/notifications'
    | '/opi'
    | '/outreach'
    | '/purchases'
    | '/admin/build/attendance'
    | '/admin/build/zones'
    | '/admin/members/$id'
    | '/admin/members/pending'
    | '/admin/notifications/templates'
    | '/admin/outreach/attendance'
    | '/admin/reports/hours'
    | '/admin/reports/opi'
    | '/admin/reports/purchases'
    | '/build/sessions/$id'
    | '/outreach/events/$id'
    | '/admin/members'
    | '/admin/opi'
    | '/admin/purchases'
    | '/admin/build/schedule/new'
    | '/admin/opi/$id/review'
    | '/admin/outreach/events/new'
    | '/admin/purchases/$id/review'
    | '/admin/build/schedule'
    | '/admin/outreach/events'
    | '/admin/outreach/individual'
    | '/admin/outreach/individual/$id/review'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/pending-approval'
    | '/signup'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/hours'
    | '/_app/profile'
    | '/auth/callback'
    | '/_app/admin/cron-jobs'
    | '/_app/admin/settings'
    | '/_app/build/check-in'
    | '/_app/build/history'
    | '/_app/notifications/preferences'
    | '/_app/opi/$id'
    | '/_app/opi/new'
    | '/_app/outreach/check-in'
    | '/_app/outreach/history'
    | '/_app/outreach/log'
    | '/_app/purchases/$id'
    | '/_app/purchases/new'
    | '/_app/admin/'
    | '/_app/build/'
    | '/_app/notifications/'
    | '/_app/opi/'
    | '/_app/outreach/'
    | '/_app/purchases/'
    | '/_app/admin/build/attendance'
    | '/_app/admin/build/zones'
    | '/_app/admin/members/$id'
    | '/_app/admin/members/pending'
    | '/_app/admin/notifications/templates'
    | '/_app/admin/outreach/attendance'
    | '/_app/admin/reports/hours'
    | '/_app/admin/reports/opi'
    | '/_app/admin/reports/purchases'
    | '/_app/build/sessions/$id'
    | '/_app/outreach/events/$id'
    | '/_app/admin/members/'
    | '/_app/admin/opi/'
    | '/_app/admin/purchases/'
    | '/_app/admin/build/schedule/new'
    | '/_app/admin/opi/$id/review'
    | '/_app/admin/outreach/events/new'
    | '/_app/admin/purchases/$id/review'
    | '/_app/admin/build/schedule/'
    | '/_app/admin/outreach/events/'
    | '/_app/admin/outreach/individual/'
    | '/_app/admin/outreach/individual/$id/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hours': {
      id: '/_app/hours'
      path: '/hours'
      fullPath: '/hours'
      preLoaderRoute: typeof AppHoursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases/': {
      id: '/_app/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AppPurchasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/': {
      id: '/_app/outreach/'
      path: '/outreach'
      fullPath: '/outreach/'
      preLoaderRoute: typeof AppOutreachIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opi/': {
      id: '/_app/opi/'
      path: '/opi'
      fullPath: '/opi/'
      preLoaderRoute: typeof AppOpiIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications/': {
      id: '/_app/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/build/': {
      id: '/_app/build/'
      path: '/build'
      fullPath: '/build/'
      preLoaderRoute: typeof AppBuildIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/purchases/new': {
      id: '/_app/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AppPurchasesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases/$id': {
      id: '/_app/purchases/$id'
      path: '/purchases/$id'
      fullPath: '/purchases/$id'
      preLoaderRoute: typeof AppPurchasesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/log': {
      id: '/_app/outreach/log'
      path: '/outreach/log'
      fullPath: '/outreach/log'
      preLoaderRoute: typeof AppOutreachLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/history': {
      id: '/_app/outreach/history'
      path: '/outreach/history'
      fullPath: '/outreach/history'
      preLoaderRoute: typeof AppOutreachHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/check-in': {
      id: '/_app/outreach/check-in'
      path: '/outreach/check-in'
      fullPath: '/outreach/check-in'
      preLoaderRoute: typeof AppOutreachCheckInRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opi/new': {
      id: '/_app/opi/new'
      path: '/opi/new'
      fullPath: '/opi/new'
      preLoaderRoute: typeof AppOpiNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opi/$id': {
      id: '/_app/opi/$id'
      path: '/opi/$id'
      fullPath: '/opi/$id'
      preLoaderRoute: typeof AppOpiIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications/preferences': {
      id: '/_app/notifications/preferences'
      path: '/notifications/preferences'
      fullPath: '/notifications/preferences'
      preLoaderRoute: typeof AppNotificationsPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/build/history': {
      id: '/_app/build/history'
      path: '/build/history'
      fullPath: '/build/history'
      preLoaderRoute: typeof AppBuildHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/build/check-in': {
      id: '/_app/build/check-in'
      path: '/build/check-in'
      fullPath: '/build/check-in'
      preLoaderRoute: typeof AppBuildCheckInRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/cron-jobs': {
      id: '/_app/admin/cron-jobs'
      path: '/cron-jobs'
      fullPath: '/admin/cron-jobs'
      preLoaderRoute: typeof AppAdminCronJobsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/purchases/': {
      id: '/_app/admin/purchases/'
      path: '/purchases'
      fullPath: '/admin/purchases/'
      preLoaderRoute: typeof AppAdminPurchasesIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/opi/': {
      id: '/_app/admin/opi/'
      path: '/opi'
      fullPath: '/admin/opi/'
      preLoaderRoute: typeof AppAdminOpiIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/members/': {
      id: '/_app/admin/members/'
      path: '/members'
      fullPath: '/admin/members/'
      preLoaderRoute: typeof AppAdminMembersIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/outreach/events/$id': {
      id: '/_app/outreach/events/$id'
      path: '/outreach/events/$id'
      fullPath: '/outreach/events/$id'
      preLoaderRoute: typeof AppOutreachEventsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/build/sessions/$id': {
      id: '/_app/build/sessions/$id'
      path: '/build/sessions/$id'
      fullPath: '/build/sessions/$id'
      preLoaderRoute: typeof AppBuildSessionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/reports/purchases': {
      id: '/_app/admin/reports/purchases'
      path: '/reports/purchases'
      fullPath: '/admin/reports/purchases'
      preLoaderRoute: typeof AppAdminReportsPurchasesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/reports/opi': {
      id: '/_app/admin/reports/opi'
      path: '/reports/opi'
      fullPath: '/admin/reports/opi'
      preLoaderRoute: typeof AppAdminReportsOpiRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/reports/hours': {
      id: '/_app/admin/reports/hours'
      path: '/reports/hours'
      fullPath: '/admin/reports/hours'
      preLoaderRoute: typeof AppAdminReportsHoursRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/outreach/attendance': {
      id: '/_app/admin/outreach/attendance'
      path: '/outreach/attendance'
      fullPath: '/admin/outreach/attendance'
      preLoaderRoute: typeof AppAdminOutreachAttendanceRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/notifications/templates': {
      id: '/_app/admin/notifications/templates'
      path: '/notifications/templates'
      fullPath: '/admin/notifications/templates'
      preLoaderRoute: typeof AppAdminNotificationsTemplatesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/members/pending': {
      id: '/_app/admin/members/pending'
      path: '/members/pending'
      fullPath: '/admin/members/pending'
      preLoaderRoute: typeof AppAdminMembersPendingRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/members/$id': {
      id: '/_app/admin/members/$id'
      path: '/members/$id'
      fullPath: '/admin/members/$id'
      preLoaderRoute: typeof AppAdminMembersIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/build/zones': {
      id: '/_app/admin/build/zones'
      path: '/build/zones'
      fullPath: '/admin/build/zones'
      preLoaderRoute: typeof AppAdminBuildZonesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/build/attendance': {
      id: '/_app/admin/build/attendance'
      path: '/build/attendance'
      fullPath: '/admin/build/attendance'
      preLoaderRoute: typeof AppAdminBuildAttendanceRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/outreach/individual/': {
      id: '/_app/admin/outreach/individual/'
      path: '/outreach/individual'
      fullPath: '/admin/outreach/individual/'
      preLoaderRoute: typeof AppAdminOutreachIndividualIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/outreach/events/': {
      id: '/_app/admin/outreach/events/'
      path: '/outreach/events'
      fullPath: '/admin/outreach/events/'
      preLoaderRoute: typeof AppAdminOutreachEventsIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/build/schedule/': {
      id: '/_app/admin/build/schedule/'
      path: '/build/schedule'
      fullPath: '/admin/build/schedule/'
      preLoaderRoute: typeof AppAdminBuildScheduleIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/purchases/$id/review': {
      id: '/_app/admin/purchases/$id/review'
      path: '/purchases/$id/review'
      fullPath: '/admin/purchases/$id/review'
      preLoaderRoute: typeof AppAdminPurchasesIdReviewRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/outreach/events/new': {
      id: '/_app/admin/outreach/events/new'
      path: '/outreach/events/new'
      fullPath: '/admin/outreach/events/new'
      preLoaderRoute: typeof AppAdminOutreachEventsNewRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/opi/$id/review': {
      id: '/_app/admin/opi/$id/review'
      path: '/opi/$id/review'
      fullPath: '/admin/opi/$id/review'
      preLoaderRoute: typeof AppAdminOpiIdReviewRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/build/schedule/new': {
      id: '/_app/admin/build/schedule/new'
      path: '/build/schedule/new'
      fullPath: '/admin/build/schedule/new'
      preLoaderRoute: typeof AppAdminBuildScheduleNewRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/outreach/individual/$id/review': {
      id: '/_app/admin/outreach/individual/$id/review'
      path: '/outreach/individual/$id/review'
      fullPath: '/admin/outreach/individual/$id/review'
      preLoaderRoute: typeof AppAdminOutreachIndividualIdReviewRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminCronJobsRoute: typeof AppAdminCronJobsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminBuildAttendanceRoute: typeof AppAdminBuildAttendanceRoute
  AppAdminBuildZonesRoute: typeof AppAdminBuildZonesRoute
  AppAdminMembersIdRoute: typeof AppAdminMembersIdRoute
  AppAdminMembersPendingRoute: typeof AppAdminMembersPendingRoute
  AppAdminNotificationsTemplatesRoute: typeof AppAdminNotificationsTemplatesRoute
  AppAdminOutreachAttendanceRoute: typeof AppAdminOutreachAttendanceRoute
  AppAdminReportsHoursRoute: typeof AppAdminReportsHoursRoute
  AppAdminReportsOpiRoute: typeof AppAdminReportsOpiRoute
  AppAdminReportsPurchasesRoute: typeof AppAdminReportsPurchasesRoute
  AppAdminMembersIndexRoute: typeof AppAdminMembersIndexRoute
  AppAdminOpiIndexRoute: typeof AppAdminOpiIndexRoute
  AppAdminPurchasesIndexRoute: typeof AppAdminPurchasesIndexRoute
  AppAdminBuildScheduleNewRoute: typeof AppAdminBuildScheduleNewRoute
  AppAdminOpiIdReviewRoute: typeof AppAdminOpiIdReviewRoute
  AppAdminOutreachEventsNewRoute: typeof AppAdminOutreachEventsNewRoute
  AppAdminPurchasesIdReviewRoute: typeof AppAdminPurchasesIdReviewRoute
  AppAdminBuildScheduleIndexRoute: typeof AppAdminBuildScheduleIndexRoute
  AppAdminOutreachEventsIndexRoute: typeof AppAdminOutreachEventsIndexRoute
  AppAdminOutreachIndividualIndexRoute: typeof AppAdminOutreachIndividualIndexRoute
  AppAdminOutreachIndividualIdReviewRoute: typeof AppAdminOutreachIndividualIdReviewRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminCronJobsRoute: AppAdminCronJobsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminBuildAttendanceRoute: AppAdminBuildAttendanceRoute,
  AppAdminBuildZonesRoute: AppAdminBuildZonesRoute,
  AppAdminMembersIdRoute: AppAdminMembersIdRoute,
  AppAdminMembersPendingRoute: AppAdminMembersPendingRoute,
  AppAdminNotificationsTemplatesRoute: AppAdminNotificationsTemplatesRoute,
  AppAdminOutreachAttendanceRoute: AppAdminOutreachAttendanceRoute,
  AppAdminReportsHoursRoute: AppAdminReportsHoursRoute,
  AppAdminReportsOpiRoute: AppAdminReportsOpiRoute,
  AppAdminReportsPurchasesRoute: AppAdminReportsPurchasesRoute,
  AppAdminMembersIndexRoute: AppAdminMembersIndexRoute,
  AppAdminOpiIndexRoute: AppAdminOpiIndexRoute,
  AppAdminPurchasesIndexRoute: AppAdminPurchasesIndexRoute,
  AppAdminBuildScheduleNewRoute: AppAdminBuildScheduleNewRoute,
  AppAdminOpiIdReviewRoute: AppAdminOpiIdReviewRoute,
  AppAdminOutreachEventsNewRoute: AppAdminOutreachEventsNewRoute,
  AppAdminPurchasesIdReviewRoute: AppAdminPurchasesIdReviewRoute,
  AppAdminBuildScheduleIndexRoute: AppAdminBuildScheduleIndexRoute,
  AppAdminOutreachEventsIndexRoute: AppAdminOutreachEventsIndexRoute,
  AppAdminOutreachIndividualIndexRoute: AppAdminOutreachIndividualIndexRoute,
  AppAdminOutreachIndividualIdReviewRoute:
    AppAdminOutreachIndividualIdReviewRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppHoursRoute: typeof AppHoursRoute
  AppProfileRoute: typeof AppProfileRoute
  AppBuildCheckInRoute: typeof AppBuildCheckInRoute
  AppBuildHistoryRoute: typeof AppBuildHistoryRoute
  AppNotificationsPreferencesRoute: typeof AppNotificationsPreferencesRoute
  AppOpiIdRoute: typeof AppOpiIdRoute
  AppOpiNewRoute: typeof AppOpiNewRoute
  AppOutreachCheckInRoute: typeof AppOutreachCheckInRoute
  AppOutreachHistoryRoute: typeof AppOutreachHistoryRoute
  AppOutreachLogRoute: typeof AppOutreachLogRoute
  AppPurchasesIdRoute: typeof AppPurchasesIdRoute
  AppPurchasesNewRoute: typeof AppPurchasesNewRoute
  AppBuildIndexRoute: typeof AppBuildIndexRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
  AppOpiIndexRoute: typeof AppOpiIndexRoute
  AppOutreachIndexRoute: typeof AppOutreachIndexRoute
  AppPurchasesIndexRoute: typeof AppPurchasesIndexRoute
  AppBuildSessionsIdRoute: typeof AppBuildSessionsIdRoute
  AppOutreachEventsIdRoute: typeof AppOutreachEventsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppHoursRoute: AppHoursRoute,
  AppProfileRoute: AppProfileRoute,
  AppBuildCheckInRoute: AppBuildCheckInRoute,
  AppBuildHistoryRoute: AppBuildHistoryRoute,
  AppNotificationsPreferencesRoute: AppNotificationsPreferencesRoute,
  AppOpiIdRoute: AppOpiIdRoute,
  AppOpiNewRoute: AppOpiNewRoute,
  AppOutreachCheckInRoute: AppOutreachCheckInRoute,
  AppOutreachHistoryRoute: AppOutreachHistoryRoute,
  AppOutreachLogRoute: AppOutreachLogRoute,
  AppPurchasesIdRoute: AppPurchasesIdRoute,
  AppPurchasesNewRoute: AppPurchasesNewRoute,
  AppBuildIndexRoute: AppBuildIndexRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
  AppOpiIndexRoute: AppOpiIndexRoute,
  AppOutreachIndexRoute: AppOutreachIndexRoute,
  AppPurchasesIndexRoute: AppPurchasesIndexRoute,
  AppBuildSessionsIdRoute: AppBuildSessionsIdRoute,
  AppOutreachEventsIdRoute: AppOutreachEventsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
